# Generated by Django 5.2.4 on 2025-08-04 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'Meeting'), ('chat', 'Chat'), ('rfq', 'RFQ'), ('quote', 'Quote')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('replied', 'Replied'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('employee_count', models.CharField(blank=True, max_length=50)),
                ('annual_revenue', models.CharField(blank=True, max_length=100)),
                ('certifications', models.JSONField(default=list)),
                ('quality_standards', models.JSONField(default=list)),
                ('audit_reports', models.JSONField(default=list)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_address', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('shipping_regions', models.JSONField(default=list)),
                ('lead_time_range', models.CharField(blank=True, max_length=100)),
                ('reliability', models.IntegerField(default=50, help_text='Reliability score from 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_time_avg', models.IntegerField(default=48, help_text='Average response time in hours')),
                ('quote_acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of accepted quotes', max_digits=5)),
                ('category', models.CharField(max_length=100)),
                ('categories', models.JSONField(default=list)),
                ('capabilities', models.JSONField(default=list)),
                ('product_catalog', models.JSONField(default=list)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_rating', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reliability', '-verification_status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('primary', 'Primary Contact'), ('sales', 'Sales Contact'), ('technical', 'Technical Contact'), ('quality', 'Quality Contact'), ('logistics', 'Logistics Contact')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('wechat', models.CharField(blank=True, max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('wechat', 'WeChat'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['supplier', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='SupplierVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Verification Initiated'), ('documents_requested', 'Documents Requested'), ('documents_received', 'Documents Received'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='initiated', max_length=20)),
                ('documents_required', models.JSONField(default=list)),
                ('documents_submitted', models.JSONField(default=dict)),
                ('review_notes', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
