# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0003_initial'),
        ('rfq', '0002_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='initiated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='related_rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rfq.rfq'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_suppliers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliercontact'),
        ),
        migrations.AddField(
            model_name='supplierverification',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierverification',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['verification_status'], name='suppliers_s_verific_89f744_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['categories'], name='suppliers_s_categor_86b76b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['region'], name='suppliers_s_region_0f663e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['reliability'], name='suppliers_s_reliabi_0fbbaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercontact',
            unique_together={('supplier', 'contact_type')},
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['supplier', 'communication_type'], name='suppliers_c_supplie_00f5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['created_at'], name='suppliers_c_created_b40366_idx'),
        ),
    ]
