# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField()),
                ('quote_deadline', models.DateTimeField(blank=True, null=True)),
                ('delivery_deadline', models.DateTimeField(blank=True, null=True)),
                ('distribution_method', models.CharField(choices=[('auto', 'Automatic - AI Matched'), ('manual', 'Manual Selection'), ('hybrid', 'Hybrid - AI + Manual')], default='auto', max_length=20)),
                ('target_supplier_count', models.IntegerField(default=10)),
                ('regions_preferred', models.JSONField(default=list)),
                ('supplier_criteria', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('distributed', 'Distributed to Suppliers'), ('quotes_received', 'Quotes Received'), ('evaluating', 'Evaluating Quotes'), ('awarded', 'Awarded'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('responses', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('viewed', 'Viewed'), ('responded', 'Responded'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
