# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfq', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqdistribution',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='rfq.rfq'),
        ),
        migrations.AddField(
            model_name='rfqdistribution',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_distributions', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='rfq_rfq_status_208c61_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['category'], name='rfq_rfq_categor_94ea1b_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['deadline'], name='rfq_rfq_deadlin_bc0c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['distribution_method'], name='rfq_rfq_distrib_a80d77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqdistribution',
            unique_together={('rfq', 'supplier')},
        ),
    ]
