# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='suppliers.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('rfq', 'supplier')},
        ),
    ]
