# Generated by Django 5.2.4 on 2025-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('original_filename', models.CharField(blank=True, help_text="The name of the file as it was on the user's computer.", max_length=255)),
                ('file_type', models.CharField(blank=True, help_text="The MIME type of the file, e.g., 'application/pdf', 'image/jpeg'.", max_length=100)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'AI Processing'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
