# Generated by Django 5.1 on 2025-07-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('projects', '0003_projectstage_alter_projectmember_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='parsed_output',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(blank=True, help_text="The name of the file as it was on the user's computer.", max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(blank=True, help_text="The MIME type of the file, e.g., 'application/pdf', 'image/jpeg'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded'), ('PROCESSING', 'AI Processing'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed')], default='UPLOADED', max_length=20),
        ),
    ]
