# Generated by Django 5.2.4 on 2025-08-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductGenome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('stage', models.CharField(
                    choices=[
                        ('created', 'Created'),
                        ('reviewed', 'Reviewed'),
                        ('approved', 'Approved'),
                        ('used', 'Used in RFQ')
                    ],
                    default='created',
                    max_length=20
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_chunks', models.ManyToManyField(blank=True, to='knowledge_base.knowledgechunk')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApparelDPGExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_composition', models.TextField(blank=True)),
                ('sizing_chart', models.JSONField(default=dict)),
                ('fit_information', models.TextField(blank=True)),
                ('construction_details', models.TextField(blank=True)),
                ('hardware_components', models.JSONField(default=dict)),
                ('colorways', models.JSONField(default=dict)),
                ('cost_breakdown', models.JSONField(default=dict)),
                ('manufacturing_data', models.JSONField(default=dict)),
                ('dpg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apparel_extension', to='dpgs.digitalproductgenome')),
            ],
        ),
        migrations.CreateModel(
            name='DPGComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the component is placed in the spec sheet')),
                ('dpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dpgs.digitalproductgenome')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='dpgs.dpgcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dpg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dpgs.digitalproductgenome')),
            ],
        ),
    ]
