# Generated by Django 5.2.4 on 2025-08-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproductgenome',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appareldpgextension',
            name='dpg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apparel_extension', to='dpgs.digitalproductgenome'),
        ),
        migrations.AddField(
            model_name='dpgcomponent',
            name='dpg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='dpgs.digitalproductgenome'),
        ),
        migrations.AddField(
            model_name='componentspecification',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='dpgs.dpgcomponent'),
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='dpg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dpgs.digitalproductgenome'),
        ),
    ]
