# Generated by Django 5.2.3 on 2025-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproductgenome',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
