# Generated by Django 5.2.4 on 2025-08-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpgs', '0002_digitalproductgenome_summary'),
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalproductgenome',
            name='knowledge_chunks',
            field=models.ManyToManyField(blank=True, to='knowledge_base.knowledgechunk'),
        ),
    ]
