# Generated by Django 5.2.4 on 2025-08-05 19:24

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('domain', models.CharField(db_index=True, max_length=50)),
                ('subdomain', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source_document', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='internal_manual', max_length=50)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
