# Generated by Django 5.2.3 on 2025-07-08 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotes_in_flight', models.IntegerField()),
                ('on_time_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('total_orders', models.IntegerField()),
                ('active_suppliers', models.IntegerField()),
                ('avg_lead_time', models.IntegerField(help_text='Average lead time in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
