# Generated by Django 5.2.4 on 2025-08-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpgs', '0002_digitalproductgenome_summary'),
        ('projects', '0003_projectstage_alter_projectmember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active_dpg',
            field=models.OneToOneField(blank=True, help_text='The DPG currently being worked on by the agent in this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_project', to='dpgs.digitalproductgenome'),
        ),
    ]
